apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend-envoy
spec:
  type: LoadBalancer
  ports:
  - name: http-listener
    port: 8000
    targetPort: 8000
    nodePort: 30080
  - name: http-admin
    port: 8001
    targetPort: 8001
    nodePort: 30081
  selector:
    app: frontend-envoy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-envoy
  template:
    metadata:
      labels:
        app: frontend-envoy
    spec:
      containers:
      - name: frontend-envoy
        image: envoyproxy/envoy:latest
        ports:
        - containerPort: 8000
        - containerPort: 8001
        command: ["/usr/local/bin/envoy"]
        args: ["-c", "/etc/envoy-config/frontend-envoy.yaml", "--service-cluster", "frontend", "--log-format", "[METADATA][%Y-%m-%d %T.%e][%t][%l][%n] %v"]
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy-config/
      volumes:
      - name: envoy-config
        configMap:
          name: frontend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  labels:
    app: frontend-envoy
data:
  frontend-envoy.yaml: |-
    # frontend envoy proxy configuration
    admin:
      access_log_path: "/var/log/acces.log"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
    static_resources:
      listeners:
      - name: frontend-http_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              generate_request_id: true
              tracing:
                operation_name: egress
              codec_type: auto
              stat_prefix: egress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/view"
                    route:
                      cluster: viewservice
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: viewservice
        connect_timeout: 5s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: viewservice
            port_value: 8100
      - name: jaeger
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: zipkin
            port_value: 9411
    tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: jaeger
          collector_endpoint: "/api/v1/spans"
          shared_span_context: false
